server:
  servlet:
    context-path: /demo #项目访问前缀
spring:
  datasource:
    name: test  #数据库名
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动
mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件